AWSTemplateFormatVersion: '2010-09-09'
Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      # AllowCredentials: true  Uncomment only if you choose a specific origin instead of the * wildcard.
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: .
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          DB_HOST: "172.17.0.2"
          DB_USER: "root"
          DB_PASSWORD: "password"
          DB_NAME: "mydatabase"
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /users
            Method: GET
        PostApi:
          Type: Api
          Properties:
            Path: /users
            Method: POST
        PutApi:
          Type: Api
          Properties:
            Path: /users
            Method: PUT
        DeleteApi:
          Type: Api
          Properties:
            Path: /users
            Method: DELETE
